---
title: "Validation_Data"
output: html_document
date: "2024-11-04"
---

# package loading

```{r}
suppressPackageStartupMessages(library(biomaRt))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(edgeR))

```

# reading validation data

```{r}

samples <- read.delim("samples.txt") #australian_melanoma_data

countData <- read.delim("counts.txt")

rownames(countData) <- countData$geneid

countData <- countData[, colnames(countData) != "geneid"]

```


```{r}

dge <- DGEList(counts=countData)

keep.exprs <- filterByExpr(dge)

dge <- dge[keep.exprs,, keep.lib.sizes=FALSE]



countData <- cpm(dge, log=T, prior.count = 1)

countData <- as.data.frame(countData)


```


```{r}

countData$gene <- rownames(countData)


ensembl <- useMart("ensembl",dataset="hsapiens_gene_ensembl")

biomart_conv <- getBM(attributes = c("ensembl_gene_id", "external_gene_name"),
                      filters = "ensembl_gene_id",
                      countData$gene,
                      mart = ensembl)
biomart_conv$external_gene_name <- gsub("\\-| ", ".", biomart_conv$external_gene_name)

countData <- countData[match(biomart_conv$ensembl_gene_id, countData$gene), ]

countData <- countData%>%
  select(-gene) %>%
  add_column(gene_symbol=biomart_conv$external_gene_name, .after = 0) %>%
  as.data.table()

countData <- countData %>% filter(!countData$gene_symbol == "")


countData_mean <- countData %>%
  group_by(gene_symbol) %>%
  summarise(across(everything(), mean, na.rm = TRUE))

countData_mean <- as.data.frame(countData_mean)

rownames(countData_mean) <- countData_mean$gene_symbol

countData_f <- countData_mean[,colnames(countData_mean) != "gene_symbol",]

countData_f <- as.data.frame(t(countData_f))

# colnames(countData_f) <- paste0("g.", colnames(countData_f))


saveRDS(countData_f, "validation_lcpm.rds")

# saveRDS(countData_f, "validation_rowcount.RDS")

```



